### ISSUE TITLE
issue with the setup channel still exist

### ISSUE THREAD

**Issue by adh319** [Adivise/NanoSpacePlus#14]
after the latest release, it seem the bug on setup channel still exist and doest fixed. i've tried to fixed but another bug come after. So the setup channel messate after the setup command execute will suddently dissapear after 3 or 4 secs. Also, can u make the bot default source is spotify instead of youtube?

**Comment by Adivise** [comment]
i don't have problem of that

**Comment by adh319** [comment]
ok.. wait, let me test the latest release again

**Comment by adh319** [comment]
@Adivise take a look at this, the setup banner and control suddently dissapear after the setup command executed. i cloned the latest commit from github and filled the .env file

![Capture](https://user-images.githubusercontent.com/53832268/194759684-be84a1c1-e7d9-4fb6-aa1f-e45ef782100c.PNG)

**Comment by Adivise** [comment]
[![Watch the video](https://media.discordapp.net/attachments/930834958069669958/1028664071496679504/7ZMXQ30JUCg-HQ.jpg)](https://www.youtube.com/watch?v=7ZMXQ30JUCg)

**Comment by adh319** [comment]
i think i found where the problem comes from
it is from mongoDB
